# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options_poll', to='polls.Poll'),
            preserve_default=False,
        ),
    ]
