# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_option_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_option', to='polls.Option'),
        ),
    ]
