# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180301_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Poll Summary',
                'verbose_name_plural': 'Polls Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('polls.poll',),
        ),
    ]
