# Generated by Django 2.0.2 on 2018-02-26 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(max_length=60)),
                ('valor', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enquete')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enquete')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
    ]
