# Generated by Django 2.0.2 on 2018-03-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='enquete',
        ),
        migrations.AlterField(
            model_name='item',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.Enquete'),
        ),
    ]
