run:
	python3 manage.py runserver 0.0.0.0:8000
migrate:
	python3 manage.py migrate
migrations:
	python3 manage.py makemigrations
user:
	python3 manage.py createsuperuser

shell:
	python3 manage.py shell

test: 
	python3 manage.py test
